export enum MESSAGE_TYPE {
  ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION",
  TWO_STEP_VERIFICATION = "TWO_STEP_AUTHENTICATION",
  ACCOUNT_RECOVERY = "ACCOUNT_RECOVERY",
  PASSWORD_RESET = "PASSWORD_RESET"
}
