export enum ErrorCode {
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	INVALID_INPUT = 'INVALID_INPUT',
	GENERAL_ERROR = 'GENERAL_ERROR'
}

export enum AuthErrorCode {
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
	ACCOUNT_PENDING_VERIFICATION = 'ACCOUNT_PENDING_VERIFICATION',
	ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
	INVALID_TOKEN = 'INVALID_TOKEN',
	TOKEN_EXPIRED = 'TOKEN_EXPIRED',
	COOLDOWN_ACTIVE = 'COOLDOWN_ACTIVE',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
	NEW_PASSWORD_SAME_AS_OLD = 'NEW_PASSWORD_SAME_AS_OLD',
	USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND'
}

export enum SessionErrorCode {
	SESSION_NOT_FOUND = 'SESSION_NOT_FOUND'
}
